trigger:
- develop
- master
- release/*
- hotfix/*

pr:
- develop
- release/*
- hotfix/*

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2022'
  steps:
  - task: UseDotNet@2
    inputs:
      version: '2.1.x'
    displayName: 'Install .NET Core 2.1'
  # .NET 5 required for GitVersion
  - task: UseDotNet@2
    inputs:
      version: '5.x'
    displayName: 'Install .NET 5'
  - powershell: |
      $ENV:CAKE_SKIP_GITVERSION=([string]::IsNullOrEmpty($ENV:SYSTEM_PULLREQUEST_PULLREQUESTID) -eq $False).ToString()
      .\build.ps1
      exit $LASTEXITCODE 
    displayName: 'Cake Build'
- job: macOS
  pool:
    vmImage: 'macOS-11'
  steps:
  - task: UseDotNet@2
    inputs:
      version: '2.1.x'
    displayName: 'Install .NET Core 2.1'
  # .NET 5 required for GitVersion
  - task: UseDotNet@2
    inputs:
      version: '5.x'
    displayName: 'Install .NET 5'
  - bash: |
      ./build.sh
    displayName: 'Cake Build'
- job: Ubuntu
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - task: UseDotNet@2
    inputs:
      version: '2.1.x'
    displayName: 'Install .NET Core 2.1'
  # .NET 5 required for GitVersion
  - task: UseDotNet@2
    inputs:
      version: '5.x'
    displayName: 'Install .NET 5'
  - bash: |
      ./build.sh --verbosity diagnostic
    displayName: 'Cake Build'